# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

DEFAULTS: &DEFAULTS
  a_default: <%= ENV['A_DEFAULT_VALUE'] %>

development:
  secret_key_base: 66c9bc410f881ed86dedb6df5ab6516a2aee5757be2c5e55b95d636c087ad33364187e31142d2c1d0b40b784f14122463ced317f8200dfa4309a656471bbfcc3
  devise_pepper: thisisadummypepper
  twilio_account_phone: +14157379164
  twilio_account_sid: <%= ENV['TWILIO_PROD_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_PROD_AUTH_TOKEN'] %>
  start_of_day_24h: <%= ENV['START_OF_DAY_24H'].to_i %>
  end_of_day_24h: <%= ENV['END_OF_DAY_24H'].to_i %>
  default_host: localhost
  session_price_per_second: <%= ENV['session_price_per_second'].to_f %>
  minimum_session_cost: <%= ENV['MINIMUM_SESSION_COST'] %>
  maximum_session_cost: <%= ENV['MAXIMUM_SESSION_COST'] %>
  minimum_invoice_charge: <%= ENV['MINIMUM_INVOICE_CHARGE'] %>
  invoicing_threshold: <%= ENV['INVOICING_THRESHOLD'].to_f %>
  stripe_secret_key: <%= ENV['STRIPE_TEST_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>
  iobridge_door_open_url: http://www.reddit.com/r/ECE/comments/371jin/are_the_majority_of_ece_jobs_in_the_power/criweyh.json
  <<: *DEFAULTS

test:
  secret_token: 97429f688377f8c5a42105dd1341be9e6907e369764d62de52ea79e32aeda972d56cfd7dd484b258742501c9c4454aac44fe67aa5dd382344f6e1def8c7a11d9
  secret_key_base: e448e614ca296edb45c48897c3a7ebc2e4b2752e779c37c77c7a2364f3d87a8dccda9e1a5e3cff06c372e5e7d50c237266d7f623bfb6d2a4fd6bdce5c398fe9b
  devise_pepper: thisisadummypepper
  twilio_account_phone: +15005550006
  twilio_account_sid: <%= ENV['TWILIO_TEST_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_TEST_AUTH_TOKEN'] %>
  start_of_day_24h: <%= 8 %>
  end_of_day_24h: <%= 23 %>
  default_host: test_host
  session_price_per_second: <%= 50 %>
  minimum_session_cost: <%= 50000 %>
  maximum_session_cost: <%= 250000 %>
  minimum_invoice_charge: <%= 6500 %>
  iobridge_door_open_url: http://www.reddit.com/r/ECE/comments/371jin/are_the_majority_of_ece_jobs_in_the_power/criweyh.json
  invoicing_threshold: <%=  500.0 %>
  stripe_secret_key: <%= ENV['STRIPE_TEST_SECRET_KEY'] %>
  stripe_publishable_key: <%= ENV['STRIPE_TEST_PUBLISHABLE_KEY'] %>
  <<: *DEFAULTS

# Do not keep production secrets in the repository; instead, read values from the environment.
production:
  stripe_secret_key: <%= ENV['STRIPE_PRODUCTION_SECRET_KEY'] %>
  secret_token: <%= ENV["RAILS_SECRET_TOKEN"] %>
  secret_key_base: <%= ENV["RAILS_SECRET_KEY_BASE"] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  start_of_day_24h: <%= ENV['START_OF_DAY_24H'].to_i %>
  end_of_day_24h: <%= ENV['END_OF_DAY_24H'] %>
  default_host: <%= ENV['DEFAULT_HOST'] %>
  twilio_account_phone: <%= ENV['TWILIO_PROD_PHONE_NUMBER'] %>
  twilio_account_sid: <%= ENV['TWILIO_PROD_ACCOUNT_SID'] %>
  twilio_auth_token: <%= ENV['TWILIO_PROD_AUTH_TOKEN'] %>
  session_price_per_second: <%= ENV['session_price_per_second'].to_f %>
  iobridge_door_open_url: <%= ENV['DOOR_OPEN_URL'] %>
  minimum_session_cost: <%= ENV['MINIMUM_SESSION_COST'].to_i %>
  maximum_session_cost: <%= ENV['MAXIMUM_SESSION_COST'].to_i %>
  minimum_invoice_charge: <%= ENV['MINIMUM_INVOICE_CHARGE'].to_i %>
  invoicing_threshold: <%= ENV['INVOICING_THRESHOLD'].to_f %>
  publishable_stripe_key: <%= ENV['STRIPE_PRODUCTION_PUBLISHABLE_KEY'] %>
  <<: *DEFAULTS
